name = "aruneko_mods_server"
author = "Aruneko"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30a5a53dee450808f7c6bf38d09b6849d3cc29cadcebd269183cc29430dc7ff8"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
