name = "aruneko_mods_server"
author = "Aruneko"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e02bb48dcc3e7a09062524161694d11c3cd2cce83c935543eb595d425db86a6"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
