name = "aruneko_mods_server"
author = "Aruneko"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6280ef16cfc7f7f0a859f2c21ab4346ee8214bfbfffe6c25a12cb27dc32e189"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
